---
title: "Advent of Code"
subtitle: "Day 2"
format: html
execute:
  keep-md: true
  message: false
  warning: false
---

# Solution in R

## Part 1

```{r}
library(tidyverse)
d <- read_delim(
  here::here("puzzle2", "data.txt"),
  delim = " ",
  col_names = c("opponent", "you")
)
```

```{r}
shape_score <- tibble(
  you = c("X", "Y", "Z"),
  shape_score = 1:3
)
```

```{r}
d
```


```{r}
key <- expand.grid(
    you = LETTERS[24:26], 
    opponent = LETTERS[1:3]
  ) |>
  mutate(result_score = c(3, 6, 0, 0, 3, 6, 6, 0, 3))
```


```{r}
d |>
  left_join(shape_score) |>
  left_join(key) |>
  mutate(score = shape_score + result_score) |>
  summarize(total = sum(score))
```

## Part 2

```{r}
needed_outcome <- tibble(
  you = LETTERS[24:26],
  result = c("lose", "draw", "win")
)
```


```{r}
key <- key |>
  mutate(
    result = case_when(
      result_score == 0 ~ "lose",
      result_score == 3 ~ "draw",
      TRUE ~ "win"
    )
  ) 
```


```{r}
d |>
  left_join(needed_outcome) |>
  select(-you) |>
  left_join(key, join_by(opponent, result)) |>
  left_join(shape_score) |>
  mutate(score = shape_score + result_score) |>
  summarize(total = sum(score))
```

# Solution in python

```{python}
import pandas as pd
import numpy as np
```

```{python}
d = pd.read_csv(
  "data.txt",
  delim_whitespace = True,
  names = ['opponent', 'you']
)
```

## Part 1

```{python}
shape_score_data = {
  "you" : ["X", "Y", "Z"],
  "shape_score" : [1, 2, 3]
}
shape_score = pd.DataFrame(data = shape_score_data)
```

```{python}
comparisons = [(o, y) for o in ["A", "B", "C"] for y in ["X", "Y", "Z"]]
key = pd.DataFrame(data = comparisons, columns = ['opponent', 'you'])
key['result_score'] = [3, 6, 0, 0, 3, 6, 6, 0, 3]
```

```{python}
scored = d.merge(
  shape_score,
  on = 'you',
  how = 'left'
).merge(
  key,
  on = ['opponent', 'you'],
  how = 'left'
)
```

```{python}
total = scored['shape_score'] + scored['result_score']
sum(total)
```

## Part 2

```{python}
needed_outcome_data = {
  "you" : ["X", "Y", "Z"],
  "result" : ["lose", "draw", "win"]
}
needed_outcome = pd.DataFrame(data = needed_outcome_data)
```

```{python}
conditions = [(key['result_score'] == 0), (key['result_score'] == 3)]
output = ['lose', 'draw']

key['result'] = np.select(conditions, output, default = 'win')
```

```{python}
scored_new = (
  d
  .merge(
    needed_outcome,
    on = 'you',
    how = 'left'
  )
  .drop('you', axis = 1)
  .merge(
    key,
    on = ['opponent', 'result'],
    how = 'left'
  )
  .merge(
    shape_score,
    on = 'you',
    how = 'left'
  )
)
```

```{python}
total_new = scored_new['shape_score'] + scored_new['result_score']
sum(total_new)
```


