---
title: "Advent of Code"
subtitle: "Day 4"
format: html
execute:
  keep-md: true
  message: false
  warning: false
---

# Solution in R

## Part 1

```{r}
library(tidyverse)

d <- read_csv(here::here("puzzle4", "data.txt"), col_names = paste0("s", 1:2))

separated <- d |>
  separate(s1, c("s1_lower", "s1_upper"), convert = TRUE) |>
  separate(s2, c("s2_lower", "s2_upper"), convert = TRUE) |>
  mutate(
    fully_contained = 
      ((s1_lower >= s2_lower) & (s1_upper <= s2_upper)) |
      ((s2_lower >= s1_lower) & (s2_upper <= s1_upper))
  ) 
  
separated |>
  count(fully_contained)
```

## Part 2

```{r}
separated |>
  mutate(
    partially_contained = (s1_upper >= s2_lower) & (s2_upper >= s1_lower)
  ) |>
  count(partially_contained)
```

# Solution in python

## Part 1

```{python}
import pandas as pd
```

```{python}
d = pd.read_csv("data.txt", sep = ",", names = ['s1', 's2'])
d[['s1_lower', 's1_upper']] = d['s1'].str.split('-', expand = True)
d[['s2_lower', 's2_upper']] = d['s2'].str.split('-', expand = True)

for column in [['s1_lower', 's1_upper', 's2_lower', 's2_upper']]:
  d[column] = d[column].astype('int')  
```

```{python}
c1 = ((d['s1_lower'] >= d['s2_lower']) & (d['s1_upper'] <= d['s2_upper']))
c2 = ((d['s2_lower'] >= d['s1_lower']) & (d['s2_upper'] <= d['s1_upper']))

(c1 | c2).sum()
```

## Part 2

```{python}
partially_contained = (d['s1_upper'] >= d['s2_lower']) & (d['s2_upper'] >= d['s1_lower'])

partially_contained.sum()
```